# This playbook could be run in various modes:
#
# 1. Install Behat, generate "behat.yml" from template and run Selenium hub.
# cibox tests
# 2. Actions from first step and run Behat tests.
# cibox tests --run
# 3. The same as second variant, but with Xvfb service started. Tests could be run without display.
# cibox tests --run --headless
---
- hosts: localhost
  gather_facts: yes
  connection: local
  become: yes

  vars_files:
    - ../config.yml
    - vars/main.yml
    - vars/tests.yml

  vars:
    run: no
    headless: no

  pre_tasks:
    - name: Check if Behat is already installed
      stat:
        path: ../vendor/behat/behat/
      register: is_vendor

    - name: Check for composer.json
      stat:
        path: ../composer.json
      register: is_composer_json

    - name: Install Behat
      shell: cd ../ && composer install
      when: not is_vendor.stat.exists and is_composer_json.stat.exists

  tasks:
    - name: Ensure Xvfb service started
      service:
        name: xvfb
        state: started
        args: :99 -ac -screen 0 1024x768x24
      when: run and headless

    - name: Ensure Selenium service started
      service:
        name: selenium
        state: started
        args: "{{ '' if headless else '-role hub' }} -log selenium.log"
      environment:
        DISPLAY: "{{ ':99' if headless else '' }}"

    - name: Wait for establish Selenium connection
      wait_for:
        port: 4444
        host: 127.0.0.1
        delay: 10

    - include: tasks/reports.yml
      when: run

    - name: Create behat.yml
      template:
        src: templates/behat.j2
        dest: ../tests/behat/behat.yml

    - name: Run Behat tests
      shell: "cd ../tests/behat && ../../bin/behat"
      ignore_errors: yes
      when: run

    - name: Create Behat report
      shell: 'if [ -s {{ reports_dir }}/behat/index.html ]; then echo "<a href=\"{{ reports_url }}/behat/index.html\" target=\"_blank\">Behat report</a>" >> {{ artifacts_file }}; fi'
      when: run
