---
- hosts: localhost
  gather_facts: yes
  connection: local
  sudo: yes

  vars_files:
    - ../config.yml
    - vars/main.yml

  tasks:
    - include_vars: "vars/environments/{{ env }}.yml"
    - include: tasks/database/remove.yml

    - name: Create config
      template:
        src: templates/wp-config.j2
        dest: ../docroot/wp-config.php

    - include: tasks/database/create.yml

    - include: tasks/wp-cli/core-install.yml
      when: not sql_workflow

    # Download and import databases.
    - include: tasks/database/import.yml
      when: sql_workflow

    # Unique way for both workflows.
    - include: tasks/super-admin.yml

    # Enable/disable configured plugins.
    - include: tasks/wp-cli/plugins.yml

    - include: tasks/wp-cli/commands.yml
